### ISSUE TITLE
Managing custom config

### ISSUE THREAD

**Issue by bngsudheer** [SoInteractive/ansible-prometheus#14]
I ran into this problem.
The role generates the config file /etc/prometheus/prometheus.yml with expected values.

As a Prometheus user, where should I put up my extra configuration?

If I update the same file  /etc/prometheus/prometheus.yml, the changes will be lost when I run the role again. 

If there's no custom configuration file, I would suggest creating a variable like prometheus_deploy_exaple_config and template the prometheus.yml file based on this variable. I could make a pull request, if you agree to this modification.

**Comment by rdemachkovych** [comment]
Looks fine, if required customization global prometheus configuration.
Feel free to add pull request with variable something like below:
{{ prometheus_custom_config | to_nice_yml }}

**Comment by bngsudheer** [comment]
Fixed in https://github.com/SoInteractive/ansible-prometheus/commit/10b483dd6069ab6e595e466f6857af0dc4569f8f
